"""add_failure_stage_to_certificates

Revision ID: e3b3f281f697
Revises: 82d86ab3fc0c
Create Date: 2026-10-07 14:56:11.861168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b3f281f697'
down_revision: Union[str, Sequence[str], None] = '82d86ab3fc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('failure_stage', sa.Enum('VALIDATION', 'GENERATION', name='failurestage', native_enum=False), nullable=True))
    op.create_index(op.f('ix_certificates_failure_stage'), 'certificates', ['failure_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_failure_stage'), table_name='certificates')
    op.drop_column('certificates', 'failure_stage')
    # ### end Alembic commands ###
